name: 'database-tests'
on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev
jobs:
  build:
    runs-on: ubuntu-latest
    env: 
       SUPABASE_API_KEY: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
       SUPABASE_DB_PASSWORD: ${{secrets.SUPABASE_DB_PASSWORD}}
       SUPABASE_
    steps:
      - uses: actions/checkout@v3
      - uses: supabase/setup-cli@v1
        with:
          version: 1.11.4
      - run: npx supabase start
      - run: npx supabase test db